import csv
import os
from datetime import datetime
from typing import List, Dict, Any

def get_saved_daily_balance_reports(limit: int = None) -> List[Dict[str, Any]]:
    reports_base_dir = "data/reports/daily_report"
    if not os.path.exists(reports_base_dir):
        return []

    reports = []
    for year_dir in os.listdir(reports_base_dir):
        year_path = os.path.join(reports_base_dir, year_dir)
        if not os.path.isdir(year_path):
            continue

        for month_dir in os.listdir(year_path):
            month_path = os.path.join(year_path, month_dir)
            if not os.path.isdir(month_path):
                continue

            for filename in os.listdir(month_path):
                if filename.endswith('.csv') and 'daily-balance-' in filename:
                    filepath = os.path.join(month_path, filename)
                    file_stats = os.stat(filepath)
                    created_time = datetime.fromtimestamp(file_stats.st_mtime)

                    start_date = None
                    end_date = None
                    if filename.startswith('daily-balance-') and filename.endswith('.csv'):
                        parts = filename.replace('daily-balance-', '').replace('.csv', '').split('-to-')
                        if len(parts) == 2:
                            try:
                                start_date = datetime.strptime(parts[0], '%Y-%m-%d').date()
                                end_date = datetime.strptime(parts[1], '%Y-%m-%d').date()
                            except ValueError:
                                pass

                    reports.append({
                        'filename': filename,
                        'filepath': filepath,
                        'created_time': created_time,
                        'start_date': start_date,
                        'end_date': end_date,
                        'file_size': file_stats.st_size,
                        'year': year_dir,
                        'month': month_dir
                    })

    reports.sort(key=lambda x: x['created_time'], reverse=True)

    if limit:
        reports = reports[:limit]

    return reports

def get_saved_tip_reports(limit: int = None) -> List[Dict[str, Any]]:
    reports_dir = "data/reports/tip_report"
    if not os.path.exists(reports_dir):
        return []

    reports = []
    for filename in os.listdir(reports_dir):
        if filename.endswith('.csv'):
            filepath = os.path.join(reports_dir, filename)
            file_stats = os.stat(filepath)
            created_time = datetime.fromtimestamp(file_stats.st_mtime)

            start_date = None
            end_date = None
            if filename.startswith('tip-report-') and filename.endswith('.csv'):
                parts = filename.replace('tip-report-', '').replace('.csv', '').split('-to-')
                if len(parts) == 2:
                    try:
                        start_date = datetime.strptime(parts[0], '%Y-%m-%d').date()
                        end_date = datetime.strptime(parts[1], '%Y-%m-%d').date()
                    except ValueError:
                        pass

            reports.append({
                'filename': filename,
                'filepath': filepath,
                'created_time': created_time,
                'start_date': start_date,
                'end_date': end_date,
                'file_size': file_stats.st_size
            })

    reports.sort(key=lambda x: x['created_time'], reverse=True)

    if limit:
        reports = reports[:limit]

    return reports

def parse_tip_report_csv(filepath: str) -> Dict[str, Any]:
    if not os.path.exists(filepath):
        return None

    with open(filepath, 'r', newline='') as csvfile:
        reader = csv.reader(csvfile)
        rows = list(reader)

    if len(rows) < 2:
        return None

    is_employee_specific = False
    employee_name = None
    employee_position = None

    if len(rows) > 2 and rows[1] and len(rows[1]) > 1 and rows[1][0] == "Employee":
        is_employee_specific = True
        employee_name = rows[1][1] if len(rows[1]) > 1 else ''
        if len(rows) > 2 and rows[2] and len(rows[2]) > 1 and rows[2][0] == "Position":
            employee_position = rows[2][1]

    report_data = {
        'title': rows[0][0] if rows[0] else 'Employee Tip Report',
        'date_range': '',
        'generated_by': '',
        'generated_at': '',
        'summary': [],
        'details': [],
        'payroll_summary': [],
        'is_employee_specific': is_employee_specific,
        'employee_name': employee_name,
        'employee_position': employee_position
    }

    for row in rows[:10]:
        if row and len(row) > 1:
            if row[0] == "Generated By":
                report_data['generated_by'] = row[1]
            elif row[0] == "Generated At":
                report_data['generated_at'] = row[1]

    if is_employee_specific:
        for i, row in enumerate(rows):
            if row and len(row) > 1 and row[0] == "Date Range":
                report_data['date_range'] = row[1]
            elif row and len(row) > 0 and row[0] == "PAYROLL SUMMARY":
                # Parse payroll summary for individual employee report (new format)
                j = i + 2
                while j < len(rows):
                    if not rows[j] or len(rows[j]) == 0 or not rows[j][0].strip():
                        j += 1
                        continue
                    if rows[j][0] in ['EMPLOYEE SUMMARY', 'Detailed Daily Breakdown by Employee']:
                        break

                    # This is a position header
                    position_name = rows[j][0].strip()
                    j += 1
                    payroll_fields = []

                    # Read the fields for this position
                    while j < len(rows) and rows[j] and len(rows[j]) >= 2:
                        if not rows[j][0].strip():
                            break
                        if rows[j][0] in ['EMPLOYEE SUMMARY', 'Detailed Daily Breakdown by Employee']:
                            break

                        key = rows[j][0].strip()
                        value = rows[j][1].strip()

                        # Check if this is another position header (no $ sign in value)
                        if value and not value.startswith('$'):
                            # This is a new position section
                            break

                        if key and value:
                            payroll_fields.append({
                                'name': key,
                                'value': value
                            })
                        j += 1

                    if payroll_fields:
                        report_data['payroll_summary'].append({
                            'employee_name': employee_name,
                            'position': position_name,
                            'fields': payroll_fields
                        })

            elif row and len(row) > 0 and row[0] == "EMPLOYEE SUMMARY":
                # Parse employee summary table (new format)
                header_idx = i + 2
                if header_idx < len(rows) and rows[header_idx] and rows[header_idx][0] == "Employee Name":
                    summary_headers = rows[header_idx]
                    for j in range(header_idx + 1, len(rows)):
                        if not rows[j] or len(rows[j]) == 0:
                            break
                        if rows[j][0] == '' or 'Detailed' in str(rows[j][0]):
                            break
                        if len(rows[j]) >= 2 and rows[j][0].strip():
                            summary_entry = {
                                'employee_name': rows[j][0].strip(),
                                'position': rows[j][1].strip() if len(rows[j]) > 1 else '',
                                'fields': []
                            }

                            for k in range(2, len(summary_headers)):
                                if k < len(rows[j]):
                                    summary_entry['fields'].append({
                                        'name': summary_headers[k].strip(),
                                        'value': rows[j][k].strip()
                                    })

                            report_data['summary'].append(summary_entry)

        # Parse detailed breakdown section
        for i, row in enumerate(rows):
            if row and len(row) > 0 and "Detailed Daily Breakdown" in str(row[0]):
                current_employee = None
                current_entries = []
                detail_headers = []

                for j in range(i + 2, len(rows)):
                    current_row = rows[j]
                    if not current_row or len(current_row) == 0 or not current_row[0]:
                        if current_employee and current_entries:
                            report_data['details'].append({
                                'employee': current_employee,
                                'entries': current_entries
                            })
                            current_employee = None
                            current_entries = []
                        continue

                    cell_value = str(current_row[0]).strip()

                    if cell_value.startswith('Employee:'):
                        if current_employee and current_entries:
                            report_data['details'].append({
                                'employee': current_employee,
                                'entries': current_entries
                            })
                        current_employee = cell_value.replace('Employee: ', '')
                        current_entries = []
                    elif cell_value == 'Date':
                        detail_headers = current_row
                        continue
                    elif cell_value == 'TOTAL':
                        continue
                    elif current_employee and cell_value:
                        if len(current_row) >= 2:
                            entry = {
                                'date': current_row[0].strip(),
                                'day': current_row[1].strip() if len(current_row) > 1 else '',
                                'fields': []
                            }

                            for k in range(2, len(detail_headers)):
                                if k < len(current_row):
                                    entry['fields'].append({
                                        'name': detail_headers[k].strip(),
                                        'value': current_row[k].strip()
                                    })

                            current_entries.append(entry)

                if current_employee and current_entries:
                    report_data['details'].append({
                        'employee': current_employee,
                        'entries': current_entries
                    })
                break

        return report_data

    report_data['date_range'] = rows[1][1] if len(rows[1]) > 1 else ''

    payroll_summary_start = None
    summary_start = None
    details_start = None

    for i, row in enumerate(rows):
        if row and len(row) > 0 and row[0] == "PAYROLL SUMMARY":
            payroll_summary_start = i
            print(f"DEBUG: Found payroll summary start at row {i}")
        elif row and len(row) > 0 and row[0] == "EMPLOYEE SUMMARY":
            summary_start = i
            print(f"DEBUG: Found employee summary start at row {i}")
        elif row and len(row) > 0 and "Detailed Daily Breakdown" in str(row[0]):
            details_start = i
            print(f"DEBUG: Found details start at row {i}")
            break

    # Parse payroll summary section
    report_data['payroll_summary'] = []
    if payroll_summary_start is not None:
        # Find the header row (should be 2 rows after PAYROLL SUMMARY title)
        header_row_idx = payroll_summary_start + 2
        if header_row_idx < len(rows) and rows[header_row_idx]:
            headers = rows[header_row_idx]
            # Parse data rows
            for i in range(header_row_idx + 1, len(rows)):
                row = rows[i]
                if not row or len(row) == 0 or not row[0].strip():
                    break
                if row[0] == 'EMPLOYEE SUMMARY' or 'No payroll summary' in str(row[0]):
                    break

                # Build payroll summary entry dynamically based on headers
                entry = {
                    'employee_name': row[0].strip() if len(row) > 0 else '',
                    'position': row[1].strip() if len(row) > 1 else '',
                    'fields': []
                }

                # Add custom fields (everything after employee name and position)
                for j in range(2, len(headers)):
                    if j < len(row):
                        entry['fields'].append({
                            'name': headers[j].strip(),
                            'value': row[j].strip()
                        })

                report_data['payroll_summary'].append(entry)

    if summary_start is not None:
        header_idx = summary_start + 2
        summary_headers = []
        if header_idx < len(rows) and rows[header_idx] and rows[header_idx][0] == "Employee Name":
            summary_headers = rows[header_idx]
            for i in range(header_idx + 1, len(rows)):
                row = rows[i]
                if not row or len(row) == 0:
                    break
                if row[0] == '' or 'Detailed' in str(row[0]):
                    break
                if len(row) >= 2 and row[0].strip():
                    summary_entry = {
                        'employee_name': row[0].strip(),
                        'position': row[1].strip() if len(row) > 1 else '',
                        'fields': []
                    }

                    for j in range(2, len(summary_headers)):
                        if j < len(row):
                            summary_entry['fields'].append({
                                'name': summary_headers[j].strip(),
                                'value': row[j].strip()
                            })

                    report_data['summary'].append(summary_entry)

    if details_start is not None:
        current_employee = None
        current_entries = []
        detail_headers = []

        for i in range(details_start + 2, len(rows)):
            row = rows[i]
            if not row or len(row) == 0 or not row[0]:
                if current_employee and current_entries:
                    report_data['details'].append({
                        'employee': current_employee,
                        'entries': current_entries
                    })
                    current_employee = None
                    current_entries = []
                continue

            cell_value = str(row[0]).strip()

            if cell_value.startswith('Employee:'):
                if current_employee and current_entries:
                    report_data['details'].append({
                        'employee': current_employee,
                        'entries': current_entries
                    })
                current_employee = cell_value.replace('Employee: ', '')
                current_entries = []
            elif cell_value == 'Date':
                detail_headers = row
                continue
            elif cell_value == 'TOTAL':
                continue
            elif current_employee and cell_value:
                if len(row) >= 2:
                    entry = {
                        'date': row[0].strip(),
                        'day': row[1].strip() if len(row) > 1 else '',
                        'fields': []
                    }

                    for k in range(2, len(detail_headers)):
                        if k < len(row):
                            entry['fields'].append({
                                'name': detail_headers[k].strip(),
                                'value': row[k].strip()
                            })

                    current_entries.append(entry)

        if current_employee and current_entries:
            report_data['details'].append({
                'employee': current_employee,
                'entries': current_entries
            })

    return report_data

def parse_daily_balance_csv(filepath: str) -> Dict[str, Any]:
    if not os.path.exists(filepath):
        return None

    with open(filepath, 'r', newline='') as csvfile:
        reader = csv.reader(csvfile)
        rows = list(reader)

    print(f"\nDEBUG parse_daily_balance_csv: filepath={filepath}", flush=True)
    print(f"DEBUG: Total rows={len(rows)}", flush=True)
    print(f"DEBUG: First 10 rows:", flush=True)
    for idx, row in enumerate(rows[:10]):
        print(f"  Row {idx}: {row}", flush=True)

    if len(rows) < 2:
        return None

    report_data = {
        'title': rows[0][0] if rows[0] else 'Consolidated Daily Balance Report',
        'date_range': rows[1][1] if len(rows[1]) > 1 else '',
        'generated_by': '',
        'generated_at': '',
        'finalized_at': '',
        'checks_efts_summary': [],
        'daily_reports': []
    }

    for row in rows[:10]:
        if row and len(row) > 1:
            if row[0] == "Generated By":
                report_data['generated_by'] = row[1]
            elif row[0] == "Generated At":
                report_data['generated_at'] = row[1]
            elif row[0] == "Finalized At":
                report_data['finalized_at'] = row[1]

    i = 3
    while i < len(rows):
        row = rows[i]

        # Parse Checks & EFT Summary section
        if row and len(row) > 0 and row[0] == 'Checks & EFT Summary':
            i += 1
            # Skip header row
            if i < len(rows) and rows[i] and rows[i][0] == 'Type':
                i += 1

            # Parse all summary entries
            while i < len(rows) and rows[i] and len(rows[i]) >= 5:
                if rows[i][0] in ['', 'Date: '] or rows[i][0].startswith('Date: '):
                    break

                report_data['checks_efts_summary'].append({
                    'type': rows[i][0],
                    'date': rows[i][1],
                    'number': rows[i][2],
                    'payable_to': rows[i][3],
                    'total': rows[i][4],
                    'memo': rows[i][5] if len(rows[i]) > 5 else ''
                })
                i += 1

            # Skip empty rows and update row variable
            while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                i += 1
            # Don't continue, fall through to check for daily reports
            if i < len(rows):
                row = rows[i]
            else:
                break

        if row and len(row) > 0 and row[0].startswith('Date: '):
            date_parts = row[0].replace('Date: ', '').split(' - ')
            report_date = date_parts[0] if len(date_parts) > 0 else ''
            day_of_week = date_parts[1] if len(date_parts) > 1 else ''

            daily_report = {
                'date': report_date,
                'day_of_week': day_of_week,
                'created_by': '',
                'finalized_at': '',
                'edited_by': '',
                'notes': '',
                'revenue_items': [],
                'expense_items': [],
                'revenue_total': 0,
                'expense_total': 0,
                'cash_over_under': 0,
                'employees': []
            }

            i += 1

            while i < len(rows) and rows[i] and len(rows[i]) > 1:
                if rows[i][0] in ['Report Created By', 'Generated By']:
                    daily_report['created_by'] = rows[i][1]
                    i += 1
                elif rows[i][0] in ['Report Finalized At', 'Finalized At']:
                    daily_report['finalized_at'] = rows[i][1]
                    i += 1
                elif rows[i][0] in ['Report Edited By', 'Last Edited By']:
                    daily_report['edited_by'] = rows[i][1]
                    i += 1
                elif rows[i][0] == 'Notes':
                    daily_report['notes'] = rows[i][1]
                    i += 1
                else:
                    break

            while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                i += 1

            if i < len(rows) and rows[i] and rows[i][0] == 'Revenue & Income':
                i += 1
                while i < len(rows) and rows[i] and len(rows[i]) >= 2:
                    print(f"DEBUG Revenue loop: i={i}, row={rows[i]}", flush=True)
                    if rows[i][0] == 'Total Revenue':
                        daily_report['revenue_total'] = rows[i][1]
                        print(f"DEBUG: Set revenue_total to {rows[i][1]}", flush=True)
                        i += 1
                        break
                    elif rows[i][0] and rows[i][0] not in ['', 'Deposits & Expenses', 'Employee Breakdown']:
                        daily_report['revenue_items'].append({
                            'name': rows[i][0],
                            'value': rows[i][1]
                        })
                    i += 1

            while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                i += 1

            if i < len(rows) and rows[i] and rows[i][0] == 'Deposits & Expenses':
                i += 1
                while i < len(rows) and rows[i] and len(rows[i]) >= 2:
                    print(f"DEBUG Expense loop: i={i}, row={rows[i]}", flush=True)
                    if rows[i][0] == 'Total Expenses':
                        daily_report['expense_total'] = rows[i][1]
                        print(f"DEBUG: Set expense_total to {rows[i][1]}", flush=True)
                        i += 1
                        break
                    elif rows[i][0] and rows[i][0] not in ['', 'Cash Over/Under', 'Employee Breakdown']:
                        daily_report['expense_items'].append({
                            'name': rows[i][0],
                            'value': rows[i][1]
                        })
                    i += 1

            while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                i += 1

            if i < len(rows) and rows[i] and rows[i][0] == 'Cash Over/Under':
                daily_report['cash_over_under'] = rows[i][1]
                print(f"DEBUG: Set cash_over_under to {rows[i][1]}", flush=True)
                i += 1

            while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                i += 1

            daily_report['checks'] = []
            daily_report['efts'] = []

            if i < len(rows) and rows[i] and rows[i][0] == 'Checks & EFT':
                i += 1

                while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                    i += 1

                if i < len(rows) and rows[i] and rows[i][0] == 'Checks':
                    i += 1

                    if i < len(rows) and rows[i] and rows[i][0] == 'Date':
                        i += 1

                        while i < len(rows) and rows[i] and len(rows[i]) >= 4:
                            if rows[i][0] in ['', 'EFT Transactions', 'Employee Breakdown'] or not rows[i][0].strip():
                                break

                            daily_report['checks'].append({
                                'date': rows[i][0],
                                'check_number': rows[i][1],
                                'payable_to': rows[i][2],
                                'total': rows[i][3],
                                'memo': rows[i][4] if len(rows[i]) > 4 else ''
                            })
                            i += 1

                while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                    i += 1

                if i < len(rows) and rows[i] and rows[i][0] == 'EFT Transactions':
                    i += 1

                    if i < len(rows) and rows[i] and rows[i][0] == 'Date':
                        i += 1

                        while i < len(rows) and rows[i] and len(rows[i]) >= 4:
                            if rows[i][0] in ['', 'Employee Breakdown'] or not rows[i][0].strip():
                                break

                            daily_report['efts'].append({
                                'date': rows[i][0],
                                'card_number': rows[i][1],
                                'payable_to': rows[i][2],
                                'total': rows[i][3],
                                'memo': rows[i][4] if len(rows[i]) > 4 else ''
                            })
                            i += 1

            while i < len(rows) and (not rows[i] or len(rows[i]) == 0 or rows[i][0] == ''):
                i += 1

            if i < len(rows) and rows[i] and rows[i][0] == 'Employee Breakdown':
                i += 1

                employee_headers = []
                if i < len(rows) and rows[i] and rows[i][0] == 'Employee Name':
                    employee_headers = rows[i]
                    i += 1

                while i < len(rows) and rows[i] and len(rows[i]) >= 2:
                    if rows[i][0] in ['', '=' * 80] or rows[i][0].startswith('Date: '):
                        break

                    employee_entry = {
                        'name': rows[i][0] if len(rows[i]) > 0 else '',
                        'position': rows[i][1] if len(rows[i]) > 1 else '',
                        'fields': []
                    }

                    for j in range(2, len(employee_headers)):
                        if j < len(rows[i]) and employee_headers[j].strip():
                            employee_entry['fields'].append({
                                'name': employee_headers[j].strip(),
                                'value': rows[i][j].strip()
                            })

                    daily_report['employees'].append(employee_entry)
                    i += 1

            print(f"\nDEBUG: Built daily_report object:", flush=True)
            print(f"  revenue_total: {daily_report['revenue_total']}", flush=True)
            print(f"  expense_total: {daily_report['expense_total']}", flush=True)
            print(f"  cash_over_under: {daily_report['cash_over_under']}", flush=True)
            print(f"  revenue_items count: {len(daily_report['revenue_items'])}", flush=True)
            print(f"  expense_items count: {len(daily_report['expense_items'])}", flush=True)

            report_data['daily_reports'].append(daily_report)

        i += 1

    print(f"\nDEBUG: Returning report_data with {len(report_data['daily_reports'])} daily reports", flush=True)
    return report_data
